### ISSUE TITLE
Modul throws UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by markus-schott** [thekampany/MMM-learnlanguage#6]
Hello, 
i´m just getting started with MagicMirror modules so maybe i´m missing something really simple.

I checked out the git repo, ran 'npm install' inside the folder, added the snippet to the config.js and changed the language to italian but when i try to start with npm start i get this output 

`[10.10.2023 12:50.08.505] [ERROR] (node:11147) UnhandledPromiseRejectionWarning: Error: Cannot find module 'request'
Require stack:
- /home/schotti/Desktop/MagicMirror/modules/MMM-learnlanguage/node_helper.js
- /home/schotti/Desktop/MagicMirror/js/app.js
- /home/schotti/Desktop/MagicMirror/js/electron.js
- /home/schotti/Desktop/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at node:internal/modules/cjs/loader:1084:15
    at Function.<anonymous> (node:electron/js2c/browser_init:2:117419)
    at Module._resolveFilename (/home/schotti/Desktop/MagicMirror/node_modules/module-alias/index.js:49:29)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/schotti/Desktop/MagicMirror/modules/MMM-learnlanguage/node_helper.js:8:15)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at loadModule (/home/schotti/Desktop/MagicMirror/js/app.js:180:19)
(Use `electron --trace-warnings ...` to show where the warning was created)
[10.10.2023 12:50.08.506] [ERROR] (node:11147) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[11147:1010/125009.070170:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
`

Thanks for your help in advance.

**Comment by thekampany** [comment]
Hi, thanks for trying out this module. Am not able to reproduce this yet. Will investigate a bit more.
Does magicmirror run normal without this module?

**Comment by KristjanESPERANTO** [comment]
The problem is that the module want's to import the package 'request' and since 'request' isn't part of MagicMirror anymore, you have to install it (on fresh systems) manually by running `npm install request` in the folder of this module.

I fixed this in PR #7. With this no manual installation will be necessary.
